apiVersion: v1
kind: Service
metadata:
  name: mlflow-nodeport
  namespace: mlops
  annotations:
    description: "NodePort MLflow para acceso desde containers Docker del training DAG"
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
