apiVersion: v1
kind: Service
metadata:
  name: minio-ui-nodeport
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30901
