# DESARROLLO: reemplazar valores antes de desplegar en producción
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mlops
type: Opaque
stringData:
  POSTGRES_USER: mlops
  POSTGRES_PASSWORD: mlops_pass
  POSTGRES_DB: mlops

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: mlops
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123

---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: mlops
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
  MLFLOW_S3_ENDPOINT_URL: http://minio:9000
  BACKEND_STORE_URI: postgresql+psycopg2://mlops:mlops_pass@postgres:5432/mlflow

---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: mlops
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: http://mlflow:5000
  DATABASE_URI: postgresql+psycopg2://mlops:mlops_pass@postgres:5432/mlops

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: mlops
type: Opaque
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://mlops:mlops_pass@postgres:5432/airflow
  AIRFLOW__CORE__FERNET_KEY: zTJpbGAhiJfJvFTtUjRQ-G7LMgG4-rVFqtMYyObFQ9Y=
  AIRFLOW__WEBSERVER__SECRET_KEY: mlops-secret-key-2026
  MLFLOW_TRACKING_URI: http://mlflow:5000

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: mlops
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin123
